language: java
jdk:
  - openjdk8
  - oraclejdk8

dist: trusty
sudo: required

services:
  - rabbitmq
  - mongodb

install: true
script:
  - cd library-service && ./gradlew clean build && cd ..
  - cd library-enrichment && ./gradlew clean build
